name: Generate Javadoc website

on:
  push:
    branches:
      - main
      - clean
  pull_request:
    branches:
      - main
      - clean

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download JavaFX SDK jars
        run: |
          mkdir lib
          curl -L -o lib/javafx-base.jar https://repo1.maven.org/maven2/org/openjfx/javafx-base/17.0.10/javafx-base-17.0.10-linux.jar
          curl -L -o lib/javafx-controls.jar https://repo1.maven.org/maven2/org/openjfx/javafx-controls/17.0.10/javafx-controls-17.0.10-linux.jar
          curl -L -o lib/javafx-graphics.jar https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/17.0.10/javafx-graphics-17.0.10-linux.jar
          curl -L -o lib/javafx-fxml.jar https://repo1.maven.org/maven2/org/openjfx/javafx-fxml/17.0.10/javafx-fxml-17.0.10-linux.jar
          curl -L -o lib/javafx-media.jar https://repo1.maven.org/maven2/org/openjfx/javafx-media/17.0.10/javafx-media-17.0.10-linux.jar

      - name: Create docs folder
        run: mkdir -p docs

      - name: Generate Javadoc
        run: |
          javadoc \
            -d docs \
            --module-path lib \
            --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.media \
            -sourcepath src/main/java \
            -subpackages fr.amu.iut.bomberman

      - name: Deploy Javadoc to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/
